language: java
branches:
  only:
  - master
deploy:
  - provider: codedeploy
    revision_type: github
    access_key_id: ASIAQL4VPKMZIGOF74G4
    secret_access_key:
      secure: TreTEpiCNV2t0jgznyuA9lUZSCNi1uHpkE3LyhSB042djj8WKEQt3Z8qdkko/ovt1mK3F7F5kkaznS/6lXPJ9clW2yi7Z7bLOy4AxhU37gx7fcB7a752kXfd/vScApkXF2tlitpLVs9LTWlEwCgWa2H9JX2ALwcuiS1PBUVn1sp9LU6UoC/WtTZ2Hjtzer16CDn/558vn3T2vm/BDf1BDf9bozbyT8gS852XDaod33gHh8YIsDiiWJG75GihddqbOCkp6izjauc33sb19X20Z9fd8eYRqKcPZMprh6S8eR1cdnG6kvM7W9vNj6jWlcrVBkYvsK3QrrSnLrh3Gh9ro2opFEb404P283dG+yKdgmME0UJpKk05LD3Snbzt0gHyeWGyLOVTbWnxiJSUiG+kcc79lVudBW0Se/KdtjuvROXUkGkoU+kaVukomBH/ZlANDKcwjF8HkcgDMMXRK3s8Xb0K261ksV3DOe1cyQSRuly0obD0K0Q2mnxdQhEN/o1JY/E1dU1U+F9EoT+X2A6h215SCUSzC3UvC/CBGLP6GMEP09un5u0WZ6jIbRdNTc+oS3TBP6EmbaCA/Jc5+bYaYjfZyz2PURmaQQPcmisIehygrnGWN13XM5/PGL0sBITadsVOO+7AMsyQ9jlSu8lkCS2g9WEEMulnaEhiXbnp7X0=
    application: unicast_backend
    deployment_group: unicast_backend
    region: us-east-1
    on:
      branch: master
  