language: java
branches:
  only:
  - master
deploy:
  - provider: codedeploy
    revision_type: github
    access_key_id: AKIAJSUFWDUTKJMJ2Y4A
    secret_access_key:
      secure: WFYarM7QLl/yuBhGcu6t0GCQrxc5jnjqnMhBDduC19bT1whMatYSSuHaVnY9zfPpGoz2yq4HFhnWvyFiGdyga5pHwod4JyY2qWgcSFU4WnSt3tfwuX4Nk4jIlT6Q8aO0reYmSplscDcIymQmh8wG2KsNB9zKsePsozho6qsfrv0pToCFSDaNoE+VQ6TCEOc/vqn3InorxyRDN+1XoLRZl4KKrBPodxFl9WwxQRJbUZa/YGqFivL+olGpxPsqAXzjxUvNttfOvL784Aqikb9+dAk6/DSUMaZK1jlxaaLgLV+mbPXM5RH/0Q0AecNFH6s+SJrGV7uq1VBHId3/9o0/PCAvUlhl5kOP84NyuzOCT1Lo+OZJAgqfZtP0iX7k8RwON21C+RiyGbnAdVHBCkt/ZLErZ4DxvZq2JPYVfNPOjeKXv5K+znH+2Qbk5TH1L7ZO/n5MRvmMvAZLSIWq4FLZetc+4NItMwl6RjFOVt/1GDRmcC4rFALTPHlxfqHGAOtp++S8ijhq2iueO5d4w+G6NKkYBhpDsg501HjGmRbIxHUW0qK6gVnSPVJiBDd06QmljMcPSGaKX1mof1rV2edZGIVzXEhFT34Dl44VLNQQlqDqLIWge23CyD11w1WvdC/E0rnsX99OYKTEIHOsJNBuhTNixfT1TmQhMJSdySsZhYY=
    application: unicast_backend
    deployment_group: unicast_backend
    region: eu-west-3
    on:
      branch: master
  