language: java
branches:
  only:
  - master
deploy:
  matrix:
  - provider: codedeploy
    revision_type: github
    access_key_id: ASIAQL4VPKMZIGOF74G4
    secret_access_key:
      secure: N1e5tlfzIDxFZEnORiusK0hMN5HG3RjmgkF5Lo1Al47WWGvUJO8JrV+54u8+K4pJ1GY2DTRvsWVzixaHIIGarfzkNXlJNpCXexsUSZF7AnfQHu9zrVaBGCn1bLXxUS3IK3HTsWMHAWoN3KGZIUCpTJE0/j5tuiati9rzdzIEL8Aa8zxzKey0rljZPlbICYZ29RLhXaldjRLDof7OrYUUxkhOl0oKJ/Uzw6/vC8FAoCjRkqyqbN3rCqU8rJLCpOVJpvHktVvYsQl0+F+tuVQSBs5Q7jwxyXjndiLixBfuwOwVoTUuRW1FCon4LdkAp2MJ0PqnkLZ9B2sE8aeg6qSE1qx6A06HtKG9HmMrwvIhRCwRSosPR7B8wn5FzZ3x7B9HAyXuJygledItdJUOrPl3idZ5fL7adUCGQE/FK+7DJrl6AvSGAtDqqNz7QsKCc08RqM3FyFZjAQxD17bpY4rUgjlkyC2m5tuF76BP4Ky+iku4aws6crMFVRI0JXLUI/nxbpzTKkezyVv8Oht00dREpi3WF90fFK8VrL2yhf7tYfL5Qtyny6GClcZXql3X2UAMDl1ySG+kKplCWa4TIvx5uRoYrGYIH9l0Gn8FnhyRGBuoFe5HmzL5yice+MDKuIPf0KGOgYPmnWl9hipn8QeVbP6Pv7v2oVLVaWfkIjL658c=
    application: unicast_backend
    deployment_group: unicast_backend
    region: us-east-1
    on:
      branch: master
  